### ISSUE TITLE
package.json "loopback-sdk-builder" wrong path

### ISSUE THREAD

**Issue by Bohmaster** [jonathan-casarrubias/native-chat-example#1]
By default, in the package.json we have this:

```
  "devDependencies": {
    "jshint": "^2.5.6",
    "loopback-sdk-builder": "file:///Volumes/backup/development/www/mean.expert/my-modules/loopback-sdk-builder",
    "nsp": "^2.1.0"
  },
```

When I run "npm install" I've been thrown an error saying that this path was not found: 
> "file:///Volumes/backup/development/www/mean.expert/my-modules/loopback-sdk-builder"

I've done this to fix it:

```
"devDependencies": {
    "jshint": "^2.5.6",
    "loopback-sdk-builder": "2.0.0-beta16",
    "nsp": "^2.1.0"
  },
```

**Comment by jonathan-casarrubias** [comment]
Hey @Bohmaster thanks for reporting this, I will be pushing a fix ASAP

Cheers!!
Jon
